### ISSUE TITLE
기타 이슈 정리 (확인용)

### ISSUE THREAD

**Issue by kang123077** [kang123077/Mars-to-Earth#41]
#####기타 이슈를 정리하기 위한 이슈 (해당 이슈로부터 다른 이슈로 파생 가능)#####

Ex )
- [x] 케릭터 시선 방향이 지속적으로 바닥이 기준이어야 함, 마우스가 장애물 위에 올라가면 흔들림이 발생

**Comment by KongJin** [comment]
2. 적용 범위에 따른 투사체 크기 조절.
3. coolDecrease에 따른 기본 공격 속도 조절.

**Comment by Hehwanny** [comment]
5. 정적으로 할당해야되는 UI와 동적으로 할당할 필요가 있는 UI에 대한 의견 필요. (각 이유 필요)
6. InGameManager에서 동적 할당을 담당하면 좋을 지 아니면 다른 스크립트를 작성할 필요가 있을지 고민

**Comment by kang123077** [comment]
- SpawnManager 관련 사항
> 맵 생성 이후에 플레이어, 몬스터가 생성되어야 함
> SpawnMonster 함수가 있다고 가정, 현재 방 or 맵에서 가진 정보를 통해 스폰 될 위치, 스폰 몬스터 수, 종류 결정

**Comment by kang123077** [comment]
- 맵 관련 이슈
1. MeshBaker 이용, 배칭 최적화 이용
> https://mentum.tistory.com/255

**Comment by kang123077** [comment]
SpawnMonster에서 몬스터를 Spawn할 때 오브젝트 풀링 사용하도록 해야할것

**Comment by KongJin** [comment]
스킬 그레네이드에 맞은적은 도트딜을 더 맞도록 수정할것,
시전이 긴 스킬은 스킬 시전을 중단할수잇도록 수정할것

**Comment by Hehwanny** [comment]
UI 관련 이슈
- [ ] 스킬 아이콘 위치 설정 및 스킬 아이콘 쿨타임 표기(Fade로 할지 Fill Amount 조절로 할 지)
- [ ] 에임 UI 고려
- [ ] 캐릭터 HP 및 적 HP 수정 필요
- [ ] HP UI 표기 방식에 따른 HP 감소 시 UI 설정 필요

**Comment by Hehwanny** [comment]
4 / 20 회의 전 회의할 내용

- [ ] 플레이어 이동 키 입력 Fix
- [ ] 시야를 가리는 장애물 투명화

**Comment by kang123077** [comment]
- [ ] 들어가면 나온 문 닫기
- [ ] 현재 방이 아닌 곳 SetActive(false)하기
- [ ] 벽으로 구르면 시야 이상하게 되는 현상

**Comment by kang123077** [comment]
스테이지 클리어 시스템 완성 됨

현재 MapManager가 가진 MapInfo에서는 현재
스테이지 넘버, 난이도, 방 갯수만 존재

방의 몬스터 스폰 갯수는 SpawnManager가 가지고 있음

적의 강해지는 정도, 강해졌을 때 반영되는 방법,
몬스터 스폰 갯수 레벨디자인은 별도로 결정해야 함

**Comment by kang123077** [comment]
- [ ] 유저 고개 돌아가는 속도?
- [ ] 수류탄 계열 아이템 사용 시 타겟 없을 때 기본 거리 설정해야 할 듯
- [ ] 수류탄 계열 아이템 착탄되는 시간을 더 빠르게하되, 멀면 느리고 가까우면 빠르게 할 수 있을지..
- [ ]

**Comment by kang123077** [comment]
- [ ] 유탄발사 업그레이드가 3 발이(툴팁엔 2발, 어느 쪽이든 바꾸면 댈듯) 장전 됨
- [ ] 그래비티 볼 쿨타임이 조금 빠른 듯
- [ ] 일렉트릭 볼 개사기 개꿀~
- [ ] 왠진 모르겠는데 여전히 난이도 적용이 됬다가 안됬다가 하는 것 같읍니다
- [ ] 지뢰? 스킬이 작동 안하는 것 같읍니다?

**Comment by Hehwanny** [comment]
- [ ] 특정 스킬 사용 시 오디오 소스 에러 관련 이슈

**Comment by kang123077** [comment]
- [ ] 그래비티 볼은 (예상했지만) 자동조준을 심각하게 부수는 문제(?)가 있음
- [ ] 고 난이도에서 공격을 맞았을 때 지나치게 화면이 붉어져서 플레이가 힘듬
(데미지 비례라 그런 듯.. 체력%를 기준으로 하면 어떨지)

**Comment by KongJin** [comment]
세환: 
모바일 해상도이슈 (아웃게임)
카드UI해상도에 따른 사이즈
비쥬얼 업데이트

민준:
타임스케일
모바일 게임오버시 스탯저장 이슈

진공
블록 댐감+
모바일 구르기
cr0 방어력 3으로
모바일 test버튼,버프 위치 , 조이스틱
모바일일때 디피컬티 조정

**Comment by Hehwanny** [comment]
- [ ] 아웃게임 UI와 인게임 UI 동기화

**Comment by kang123077** [comment]
@KongJin 
- [ ] 평타를 발사하는 즉시 달리기 시작하면 달리는 도중에도 평타가 써짐(PC, 모바일은 모름)
- [ ] 움직이기 시작한 직후에(아직 속력이 낮을 때) 구르면 굉장히 짧은 거리만 구름
@Hehwanny 
- [ ] 스킬 아이콘도 Cramp(스프라이트 속성) 체크 할 필요

**Comment by kang123077** [comment]
- [ ] MassShooting의 데미지 계수가 낮은 것 같음. 기본 대미지는 낮아도 계수는 조금 높여도 좋을 듯
- [ ] 유저의 dmg가 강해지면 넉백이 늘어나는 것 같은데 데미지 80쯤 가니까 넉백이 너무 강해짐
- [ ] 바뀐 모바일 시야 회전(꾹 누르고 있으면 해당 방향으로 계속 도는 것)은 호불호가 조금 갈릴 듯..? 뭐가 나은지 확신이 없음
- [ ] 몬스터의 Speed 증가 속도가 생각 이상으로 빠름.. 조금 낮출 필요가 있을듯
- [ ] Difficulty (Alert Level)의 시간에 따른 증가 속도 완화해야할듯
- [ ] 부활 횟수를 소모하고 다음 스테이지로 가니까 초기화 되서 스테이지당 1회 부활 가능 (이게 맞는지?)

**Comment by kang123077** [comment]
- [ ] 모든 스킬을 다 강화하니까 마지막으로 강화된 스킬이 한번 더 강화되면서 에러가 뜸 Out of Array?
- [ ] 강화된 가디언 스킬 (주변 도는거) 를 사용하면 에러가 뜸.

**Comment by kang123077** [comment]
- [ ] 보스의 잡기 패턴시 데미지가 10 고정이라 후반에 가면 간지럽네용
- [ ] 디스토션 강화 추가 ( 쿨타임 감소? )
- [ ] 블록 강화 추가 ( 데미지, 범위 증가 )

**Comment by kang123077** [comment]
공통
- [ ] 용량 낮추기? (빌드시 포함이 안되서 의미가 있는지는...)
- [ ] bgm

**Comment by Hehwanny** [comment]
@kang123077 

- [ ] 보스 방 식별
- [ ] 들린 방 표시 (해당 영역이 어려울 시 그냥 보스 방 표시만)

**Comment by KongJin** [comment]
- [ ] 모바일 공격을 자동으로 유지하게 변경 (간단한 조작으로 화면 전환과 공격을 한번에 할 수 있습니다.)
